version: '3.8'
services:
  web_server:
    image: php:8.2-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database_server
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Optioneel: uncomment als je debugging nodig hebt
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

  database_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123!@#"
    ports:
      - "1435:1433"
